Repository ToastitProject/Toastit, pull requests merged in 2024-09, with the labels that each got.

#98 🔀 Merge : "feature/categorysearch 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/basecocktail/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/entity/CocktailDocument.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/repository/CocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/repository/custom/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/repository/custom/Impl/CustomCocktailRepositoryImpl.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/service/impl/CocktailServiceImpl.java
  src/main/resources/static/css/basecocktail/basecocktail.css
  src/main/resources/static/js/basecocktail/baseLike.js
  src/main/resources/templates/feature/basecocktail/cocktailComplex-form.html
  src/main/resources/templates/feature/basecocktail/cocktailDetails-view.html
  src/main/resources/templates/feature/basecocktail/cocktailGlass.html
  src/main/resources/templates/feature/basecocktail/cocktailIngredient.html
  src/main/resources/templates/feature/basecocktail/cocktailList-form.html
  src/main/resources/templates/feature/basecocktail/cocktailType.html
  src/main/resources/templates/feature/basecocktail/name.html
  src/main/resources/templates/feature/basecocktail/random-view.html
  src/main/resources/templates/feature/basecocktail/random.html
Labels: 📖 Docs, 🛠️ Refactor, 📛 Rename

#100 🔀 Merge : "feature/trendCocktail 브랜치 병합"
  build.gradle
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/controller/GetDataController.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/controller/TrendCocktailController.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/dto/TrendCocktailDTO.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/entity/TrendCocktail.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/repository/TrendCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/service/TrendCocktailService.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/service/impl/TrendCocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/global/config/naverdatasearch/AppConfig.java
  src/main/java/alcoholboot/toastit/global/config/security/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/templates/feature/api/getData.html
  src/main/resources/templates/index.html
Labels: ✨ Feat, 💄 Design

#102 🔀 Merge : "feature/trendCocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/CraftCocktailController.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/entity/CraftCocktailEntity.java
  src/main/java/alcoholboot/toastit/feature/user/controller/FollowController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/UserController.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Like.java
  src/main/java/alcoholboot/toastit/feature/user/entity/LikeEntity.java
  src/main/java/alcoholboot/toastit/feature/user/repository/FollowRepository.java
  src/main/java/alcoholboot/toastit/feature/user/repository/LikeRepository.java
  src/main/java/alcoholboot/toastit/feature/user/service/LikeService.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/LikeServiceImpl.java
  src/main/java/alcoholboot/toastit/global/config/aws/AwsConfig.java
  src/main/resources/static/css/basecocktail/basecocktailrandom.css
Labels: 📖 Docs, 🐞 Fix, 🛠️ Refactor, 💄 Design

#104 ♻️ Refactor : "User 도메인 패키지 및 코드 구조 조정"
  src/main/java/alcoholboot/toastit/auth/controller/AuthController.java
  src/main/java/alcoholboot/toastit/auth/jwt/service/Impl/TokenRenewalServiceImpl.java
  src/main/java/alcoholboot/toastit/auth/jwt/service/Impl/TokenServiceImpl.java
  src/main/java/alcoholboot/toastit/auth/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/alcoholboot/toastit/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/alcoholboot/toastit/auth/service/AuthService.java
  src/main/java/alcoholboot/toastit/auth/service/impl/AuthServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/CraftCocktailController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/FollowController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/UserController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/request/EmailCheckRequest.java
  src/main/java/alcoholboot/toastit/feature/user/controller/request/EmailSendRequest.java
  src/main/java/alcoholboot/toastit/feature/user/controller/request/UserJoinRequest.java
  src/main/java/alcoholboot/toastit/feature/user/controller/request/UserLoginRequest.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Follow.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Like.java
  src/main/java/alcoholboot/toastit/feature/user/domain/User.java
  src/main/java/alcoholboot/toastit/feature/user/entity/FollowEntity.java
  src/main/java/alcoholboot/toastit/feature/user/entity/LikeEntity.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/java/alcoholboot/toastit/feature/user/repository/FollowRepository.java
  src/main/java/alcoholboot/toastit/feature/user/repository/LikeRepository.java
  src/main/java/alcoholboot/toastit/feature/user/repository/UserRepository.java
  src/main/java/alcoholboot/toastit/feature/user/service/FollowService.java
  src/main/java/alcoholboot/toastit/feature/user/service/LikeService.java
  src/main/java/alcoholboot/toastit/feature/user/service/UserManagementService.java
  src/main/java/alcoholboot/toastit/feature/user/service/UserProfileImageService.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/FollowServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/LikeServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserManagementServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserProfileImageServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/type/Authority.java
  src/main/java/alcoholboot/toastit/feature/user/util/RandomNickname.java
  src/main/java/alcoholboot/toastit/global/config/security/SecurityConfig.java
  src/main/resources/static/css/auth/join-form.css
  src/main/resources/static/css/auth/login-form.css
  src/main/resources/static/js/auth/join-form.js
  src/main/resources/templates/auth/join-form.html
  src/main/resources/templates/auth/login-form.html
  src/main/resources/templates/auth/resign-form.html
  src/main/resources/templates/feature/user/loginForm1.html
  src/main/resources/templates/fragment/navbar-fragment.html
  src/main/resources/templates/user/edit-form.html
  src/main/resources/templates/user/following-recipes.html
  src/main/resources/templates/user/mypage-form.html
  src/main/resources/templates/user/password-find-form.html
  src/test/java/alcoholboot/toastit/feature/user/controller/LikeControllerTest.java
  src/test/java/alcoholboot/toastit/feature/user/service/UserManagementServiceImplTest.java
Labels: 🛠️ Refactor, 💄 Design

#107 🔀 Merge : "feature/trendCocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/controller/GetDataController.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/controller/TrendCocktailController.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/dto/TrendCocktailDTO.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/entity/TrendCocktail.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/repository/TrendCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/service/TrendCocktailService.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/service/impl/TrendCocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/global/config/api/AppConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/templates/index.html
  src/main/resources/templates/trendcocktail/search-data.html
Labels: 🛠️ Refactor

#105 🔀 Merge : "feature/categorysearch 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/basecocktail/controller/CocktailController.java
  src/main/resources/static/css/fragment/navbar-fragment.css
  src/main/resources/static/image/LIKELION_brandsymbol_black.png
  src/main/resources/static/image/github-mark.svg
  src/main/resources/static/js/basecocktail/baseLike.js
  src/main/resources/templates/feature/basecocktail/allList-form.html
  src/main/resources/templates/feature/basecocktail/detail-view.html
  src/main/resources/templates/feature/basecocktail/random-view.html
  src/main/resources/templates/feature/basecocktail/search-form.html
  src/main/resources/templates/fragment/footer.html
Labels: 🐞 Fix, 🛠️ Refactor, 💄 Design

#108 🔀 Merge : "feature/security 브랜치 병합"
  package.json
  src/main/java/alcoholboot/toastit/auth/controller/AuthController.java
  src/main/java/alcoholboot/toastit/auth/controller/RecoveryController.java
  src/main/java/alcoholboot/toastit/auth/controller/request/AuthJoinRequest.java
  src/main/java/alcoholboot/toastit/auth/controller/request/AuthLoginRequest.java
  src/main/java/alcoholboot/toastit/auth/email/controller/EmailController.java
  src/main/java/alcoholboot/toastit/auth/email/controller/request/EmailCheckRequest.java
  src/main/java/alcoholboot/toastit/auth/email/controller/request/EmailSendRequest.java
  src/main/java/alcoholboot/toastit/auth/email/service/EmailService.java
  src/main/java/alcoholboot/toastit/auth/email/service/impl/EmailServiceImpl.java
  src/main/java/alcoholboot/toastit/auth/service/AuthService.java
  src/main/java/alcoholboot/toastit/auth/service/impl/AuthServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/repository/UserRepository.java
  src/main/java/alcoholboot/toastit/feature/user/service/UserManagementService.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserManagementServiceImpl.java
  src/main/java/alcoholboot/toastit/global/config/security/SecurityConfig.java
  src/main/resources/static/css/fragment/navbar-fragment.css
  src/main/resources/templates/auth/join-form.html
  src/main/resources/templates/auth/login-form.html
  src/main/resources/templates/auth/new-password-form.html
  src/main/resources/templates/auth/password-reset-form.html
  src/main/resources/templates/auth/password-reset-success.html
  src/main/resources/templates/auth/password-verify-form.html
  src/main/resources/templates/auth/resign-form.html
  src/main/resources/templates/email/mail-form.html
  src/main/resources/templates/index.html
Labels: ✨ Feat, 🛠️ Refactor, 💄 Design

#110 🔀 Merge : "feature/design 브랜치 병합"
  src/main/resources/templates/auth/login-form.html
  src/main/resources/templates/index.html
Labels: 📖 Docs, 💄 Design

#111 🔀 Merge : "feature/basecocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/basecocktail/controller/CocktailController.java
  src/main/resources/static/css/basecocktail/basecocktail.css
  src/main/resources/static/css/fragment/footer-fragment.css
  src/main/resources/static/css/fragment/navbar-fragment.css
  src/main/resources/templates/basecocktail/allList-form.html
  src/main/resources/templates/basecocktail/detail-view.html
  src/main/resources/templates/basecocktail/random-view.html
  src/main/resources/templates/basecocktail/search-form.html
  src/main/resources/templates/feature/api/weather.html
  src/main/resources/templates/feature/craftcocktail/craftdetail.html
  src/main/resources/templates/feature/craftcocktail/craftmain.html
  src/main/resources/templates/feature/craftcocktail/edit.html
  src/main/resources/templates/feature/craftcocktail/write.html
  src/main/resources/templates/feature/seasonalcocktail/recipe-preview.html
  src/main/resources/templates/index.html
Labels: 📛 Rename, 💄 Design

#112 🔀 Merge : "feature/custom브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/CraftCocktailController.java
  src/main/resources/templates/craftcocktail/craftdetail.html
  src/main/resources/templates/craftcocktail/craftmain.html
  src/main/resources/templates/craftcocktail/edit.html
  src/main/resources/templates/craftcocktail/write.html
Labels: 👷 Chore

#113 🔀 Merge : "feature/climatecocktail 브랜치 병합"
  build.gradle
  src/main/java/alcoholboot/toastit/ToastitApplication.java
  src/main/java/alcoholboot/toastit/feature/api/dto/WeatherItemDTO.java
  src/main/java/alcoholboot/toastit/feature/api/repository/WeatherMapper.java
  src/main/java/alcoholboot/toastit/feature/api/service/WeatherService.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/controller/WeatherController.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/dto/AreaRequestDTO.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/dto/LatXLngY.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/dto/WeatherApiResponseDTO.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/dto/WeatherBodyDTO.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/dto/WeatherHeaderDTO.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/dto/WeatherItemDTO.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/dto/WeatherItemsDTO.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/dto/WeatherResponseDTO.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/entity/AreaEntity.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/entity/RecommendByWeatherEntity.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/entity/WeatherEntity.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/repository/RecommendByWeatherRepository.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/repository/WeatherRepository.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/scheduler/WeatherScheduler.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/service/RecommendByWeatherService.java
  src/main/java/alcoholboot/toastit/feature/climatecocktail/service/WeatherService.java
  src/main/java/alcoholboot/toastit/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/templates/climatecocktail/climatecocktail-view.html
  src/main/resources/templates/feature/api/mappers/WeatherMapper.xml
  src/main/resources/templates/feature/api/weather.html
Labels: ✨ Feat, 🐞 Fix, 🛠️ Refactor, 💄 Design

#114 🔀 Merge : "feature/basecocktail 브랜치 병합"
  src/main/resources/static/css/basecocktail/basecocktail.css
  src/main/resources/static/css/basecocktail/basecocktaildetail.css
  src/main/resources/static/css/basecocktail/basecocktailrandom.css
  src/main/resources/static/css/fragment/footer-fragment.css
  src/main/resources/templates/basecocktail/detail-view.html
  src/main/resources/templates/fragment/footer.html
  src/main/resources/templates/index.html
Labels: 🐞 Fix, 💄 Design

#115 🔀 Merge : "feature/security 브랜치 병합"
  src/main/java/alcoholboot/toastit/auth/controller/RecoveryController.java
  src/main/java/alcoholboot/toastit/auth/email/controller/EmailController.java
  src/main/java/alcoholboot/toastit/auth/email/service/impl/EmailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/UserManagementService.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserManagementServiceImpl.java
  src/main/resources/templates/auth/mail-form.html
  src/main/resources/templates/auth/password-reset-form.html
  src/main/resources/templates/auth/password-verify-form.html
Labels: ✨ Feat, 🐞 Fix, 🛠️ Refactor, 💄 Design

#117 🔀 Merge : "feature/security 브랜치 병합"
  src/main/java/alcoholboot/toastit/auth/controller/AuthController.java
  src/main/java/alcoholboot/toastit/auth/controller/RecoveryController.java
  src/main/resources/templates/auth/password-reset-form.html
  src/main/resources/templates/auth/password-verify-form.html
Labels: ❗️ HOTFIX, 🛠️ Refactor

#122 🔀 Merge : "feature/infra 브랜치 병합"
  .gitignore
  package-lock.json
  package.json
Labels: ⚙️ Config

#125 🔀 Merge : "feature/localcocktail 브랜치 병합"
  src/main/resources/templates/localcocktail/cocktail-view.html
Labels: 💄 Design

#126 🚑 Hotfix : "컨트롤러 타임리프 경로 문제 버그 수정"
  src/main/java/alcoholboot/toastit/feature/localcocktail/controller/LocationController.java
Labels: ❗️ HOTFIX

#127 🔀 Merge : "feature/basecocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/basecocktail/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/repository/custom/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/repository/custom/Impl/CustomCocktailRepositoryImpl.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/service/impl/CocktailServiceImpl.java
Labels: ✨ Feat

#129 🔀 Merge : "feature/custom브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/CraftCocktailController.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/request/CraftCocktailCreateRequest.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/domain/CraftCocktail.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/entity/CraftCocktailEntity.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/entity/IngredientEntity.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/repository/CraftCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/service/CraftCocktailService.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/service/impl/CraftCocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/seasonalcocktail/controller/SeasonalCocktailController.java
  src/main/java/alcoholboot/toastit/feature/seasonalcocktail/service/SeasonalCocktailService.java
  src/main/java/alcoholboot/toastit/feature/seasonalcocktail/service/impl/SeasonalCocktailServiceImpl.java
  src/main/resources/templates/craftcocktail/craftmain.html
  src/main/resources/templates/error.html
  src/main/resources/templates/feature/seasonalcocktail/recipe-preview.html
Labels: 📖 Docs, ✨ Feat, 💄 Design

#131 🔀 Merge : "feature/basecocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/basecocktail/controller/CocktailController.java
  src/main/resources/static/css/basecocktail/basecocktail.css
Labels: 🛠️ Refactor, 💄 Design

#133 🔀 Merge : "feature/commenting 브랜치 병합"
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/java/alcoholboot/toastit/feature/basecocktail/service/impl/CocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/image/service/ImageService.java
  src/main/java/alcoholboot/toastit/feature/image/service/impl/CloudStorageServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/controller/GetDataController.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/controller/TrendCocktailController.java
  src/main/java/alcoholboot/toastit/feature/trendcocktail/service/impl/TrendCocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/controller/FollowController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/UserController.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/FollowServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/LikeServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserManagementServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserProfileImageServiceImpl.java
Labels: 📖 Docs

#134 💡 Comment : "Infra 패키지 가이드 라인 작성"
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/java/alcoholboot/toastit/global/config/api/AppConfig.java
  src/main/java/alcoholboot/toastit/global/config/aws/AwsConfig.java
  src/main/java/alcoholboot/toastit/global/config/mongo/MongoConfig.java
  src/main/java/alcoholboot/toastit/global/config/mongo/converter/DateToLocalDateTimeConverter.java
  src/main/java/alcoholboot/toastit/global/config/properties/PropertyConfig.java
  src/main/java/alcoholboot/toastit/global/config/redis/RedisConfig.java
  src/main/java/alcoholboot/toastit/infra/auth/controller/AuthController.java
  src/main/java/alcoholboot/toastit/infra/auth/controller/RecoveryController.java
  src/main/java/alcoholboot/toastit/infra/auth/controller/request/AuthJoinRequest.java
  src/main/java/alcoholboot/toastit/infra/auth/controller/request/AuthLoginRequest.java
  src/main/java/alcoholboot/toastit/infra/auth/service/AuthService.java
  src/main/java/alcoholboot/toastit/infra/auth/service/impl/AuthServiceImpl.java
  src/main/java/alcoholboot/toastit/infra/core/PrincipalDetails.java
  src/main/java/alcoholboot/toastit/infra/email/controller/EmailController.java
  src/main/java/alcoholboot/toastit/infra/email/controller/request/EmailCheckRequest.java
  src/main/java/alcoholboot/toastit/infra/email/controller/request/EmailSendRequest.java
  src/main/java/alcoholboot/toastit/infra/email/service/EmailService.java
  src/main/java/alcoholboot/toastit/infra/email/service/VerificationService.java
  src/main/java/alcoholboot/toastit/infra/email/service/impl/EmailServiceImpl.java
  src/main/java/alcoholboot/toastit/infra/email/service/impl/VerificationServiceImpl.java
  src/main/java/alcoholboot/toastit/infra/email/util/RandomAuthCode.java
  src/main/java/alcoholboot/toastit/infra/oauth2/domain/OAuthAttributes.java
  src/main/java/alcoholboot/toastit/infra/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/alcoholboot/toastit/infra/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/alcoholboot/toastit/infra/oauth2/service/CustomOAuth2UserService.java
Labels: 📖 Docs

#135 🔀 Merge : "feature/user 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/user/controller/FollowController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/UserController.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Follow.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Like.java
  src/main/java/alcoholboot/toastit/feature/user/domain/User.java
  src/main/java/alcoholboot/toastit/feature/user/entity/FollowEntity.java
  src/main/java/alcoholboot/toastit/feature/user/entity/LikeEntity.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/java/alcoholboot/toastit/feature/user/repository/FollowRepository.java
  src/main/java/alcoholboot/toastit/feature/user/repository/LikeRepository.java
  src/main/java/alcoholboot/toastit/feature/user/repository/UserRepository.java
  src/main/java/alcoholboot/toastit/feature/user/service/FollowService.java
  src/main/java/alcoholboot/toastit/feature/user/service/LikeService.java
  src/main/java/alcoholboot/toastit/feature/user/service/UserManagementService.java
  src/main/java/alcoholboot/toastit/feature/user/service/UserProfileImageService.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/FollowServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/LikeServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserManagementServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserProfileImageServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/type/Authority.java
  src/main/java/alcoholboot/toastit/feature/user/util/RandomNickname.java
  src/main/resources/templates/auth/join-form.html
  src/main/resources/templates/user/edit-form.html
  src/main/resources/templates/user/following-recipes.html
  src/main/resources/templates/user/mypage-form.html
  src/main/resources/templates/user/password-find-form.html
  src/main/resources/templates/user/recipe-manage-view.html
Labels: 📖 Docs

#136 🔀 Merge : "feature/basecocktail 브랜치 병합"
  src/main/resources/static/css/basecocktail/basecocktail.css
  src/main/resources/static/css/basecocktail/basecocktaildetail.css
  src/main/resources/static/js/basecocktail/list.js
  src/main/resources/static/js/basecocktail/pageUrl.js
  src/main/resources/templates/basecocktail/allList-form.html
  src/main/resources/templates/basecocktail/detail-view.html
  src/main/resources/templates/basecocktail/random-view.html
  src/main/resources/templates/basecocktail/search-form.html
  src/main/resources/templates/craftcocktail/craftdetail.html
  src/main/resources/templates/craftcocktail/craftmain.html
  src/main/resources/templates/craftcocktail/edit.html
  src/main/resources/templates/craftcocktail/write.html
  src/main/resources/templates/feature/seasonalcocktail/recipe-preview.html
  src/main/resources/templates/index.html
Labels: 🐞 Fix, 🛠️ Refactor, 💄 Design

#137 🔀 Merge : "feature/custom브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/seasonalcocktail/controller/SeasonalCocktailController.java
  src/main/resources/templates/craftcocktail/craftdetail.html
  src/main/resources/templates/craftcocktail/craftmain.html
  src/main/resources/templates/craftcocktail/write.html
  src/main/resources/templates/seasonalcocktail/recipe-preview.html
  src/test/resources/application-test.yml
Labels: 💄 Design

#138 🔀 Merge : "feature/basecocktail 브랜치 병합"
  src/main/resources/static/css/basecocktail/basecocktaildetail.css
Labels: 💄 Design

#139 🔀 Merge : "feature/design 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/user/controller/UserController.java
  src/main/resources/static/image/background/find-craftcocktail.png
  src/main/resources/static/image/background/follow-image.png
  src/main/resources/static/image/background/like-cocktail.png
  src/main/resources/static/image/background/share-cocktail.png
  src/main/resources/templates/index.html
  src/main/resources/templates/localcocktail/cocktail-view.html
  src/main/resources/templates/user/following-recipes.html
  src/main/resources/templates/user/mypage-form.html
  src/main/resources/templates/user/recipe-manage-view.html
Labels: 🐞 Fix, 📛 Rename, 💄 Design

#140 Merge : "feature/craftcocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/seasonalcocktail/controller/SeasonalCocktailController.java
  src/main/resources/static/css/basecocktail/basecocktail.css
  src/main/resources/templates/craftcocktail/craftmain.html
  src/main/resources/templates/weathercocktail/weathercocktail-view.html
Labels: 💄 Design, 👷 Chore

#141 🔀 Merge : "feature/basecocktail 브랜치 병합"
  src/main/resources/static/css/basecocktail/basecocktail.css
Labels: 💄 Design

#144 🔀 Merge : "feature/design 브랜치 병합"
  src/main/resources/templates/user/following-recipes.html
  src/main/resources/templates/user/recipe-manage-view.html
Labels: 💄 Design

#146 🔀 Merge : "feature/design 브랜치 병합"
  src/main/resources/templates/user/edit-form.html
Labels: 🐞 Fix
