Repository ToastitProject/Toastit, pull requests merged in 2024-08, with the labels that each got.

#8 🔀 Merge : "feature/user 브랜치 병합"
  src/main/java/alcoholboot/toastit/auth/jwt/domain/Token.java
  src/main/java/alcoholboot/toastit/auth/jwt/entity/TokenEntity.java
  src/main/java/alcoholboot/toastit/auth/jwt/repository/Impl/TokenRepositoryImpl.java
  src/main/java/alcoholboot/toastit/auth/jwt/service/Impl/TokenServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/README.md
  src/main/java/alcoholboot/toastit/feature/user/domain/User.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/java/alcoholboot/toastit/feature/user/type/Authority.java
Labels: ✨ Feat

#22 Origin/feature/categorysearch
  build.gradle
  src/main/java/alcoholboot/toastit/feature/categorysearch/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/domain/Cocktail.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/entity/CocktailEntity.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/repository/CocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/service/impl/CocktailServiceImpl.java
  src/main/resources/templates/cocktaildefault/cocktailDetails.html
  src/main/resources/templates/cocktaildefault/cocktailList.html
  src/test/java/alcoholboot/toastit/feature/categorysearch/controller/CocktailControllerTest.java
  src/test/java/alcoholboot/toastit/feature/categorysearch/service/impl/CocktailServiceTest.java
Labels: ✨ Feat

#27 Feature/custom
  src/main/java/alcoholboot/toastit/feature/customcocktail/controller/CustomCocktailController.java
  src/main/java/alcoholboot/toastit/feature/customcocktail/domain/CustomCocktail.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/resources/templates/feature/customcocktail/custommain.html
  src/main/resources/templates/feature/customcocktail/write.html
Labels: ✨ Feat

#29 🔀 Merge : "feature/userResign 브랜치 병합"
  build.gradle
  package-lock.json
  package.json
  src/main/java/alcoholboot/toastit/feature/amazonimage/service/S3imageUploadService.java
  src/main/java/alcoholboot/toastit/feature/customcocktail/domain/CustomCocktail.java
  src/main/java/alcoholboot/toastit/feature/customcocktail/repository/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/customcocktail/service/CustomCocktailService.java
  src/main/java/alcoholboot/toastit/feature/user/controller/FollowController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Follow.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Like.java
  src/main/java/alcoholboot/toastit/feature/user/entity/FollowEntity.java
  src/main/java/alcoholboot/toastit/feature/user/entity/LikeEntity.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/java/alcoholboot/toastit/feature/user/repository/FollowRepository.java
  src/main/java/alcoholboot/toastit/feature/user/repository/LikeRepository.java
  src/main/java/alcoholboot/toastit/feature/user/service/FollowService.java
  src/main/java/alcoholboot/toastit/feature/user/service/LikeService.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/FollowServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/LikeServiceImpl.java
  src/main/java/alcoholboot/toastit/global/config/security/SecurityConfig.java
  src/main/resources/templates/feature/customcocktail/customdetail.html
  src/main/resources/templates/feature/user/editForm.html
  src/main/resources/templates/feature/user/mypageForm.html
  src/main/resources/templates/feature/user/resignForm.html
  src/main/resources/templates/fragment/navbar-fragment.html
  src/main/resources/templates/image.html
Labels: ✨ Feat

#30 🔀 Merge : "feature/userResign 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/categorysearch/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/repository/CocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/service/impl/CocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/customcocktail/controller/CustomCocktailController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Like.java
  src/main/java/alcoholboot/toastit/feature/user/entity/LikeEntity.java
  src/main/java/alcoholboot/toastit/feature/user/repository/LikeRepository.java
  src/main/java/alcoholboot/toastit/feature/user/service/LikeService.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/LikeServiceImpl.java
  src/main/resources/templates/feature/categorysearch/cocktailDetails.html
  src/main/resources/templates/feature/categorysearch/cocktailList.html
  src/main/resources/templates/feature/customcocktail/customdetail.html
  src/main/resources/templates/fragment/navbar-fragment.html
Labels: ✨ Feat

#32 🔀 Merge : "Feature/categorysearch 병합"
  src/main/java/alcoholboot/toastit/feature/categorysearch/repository/CocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/repository/custom/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/repository/custom/Impl/CustomCocktailRepositoryImpl.java
  src/main/java/alcoholboot/toastit/feature/categorysearch/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/domain/Cocktail.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/entity/CocktailDocument.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/CocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/Impl/CustomCocktailRepositoryImpl.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/resources/static/css/defaultcocktail/defaultcocktail.css
  src/main/resources/templates/feature/categorysearch/cocktailIngredient.html
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailDetails.html
  src/main/resources/templates/feature/defaultcocktail/cocktailGlass.html
  src/main/resources/templates/feature/defaultcocktail/cocktailIngredient.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
  src/main/resources/templates/feature/defaultcocktail/cocktailType.html
  src/test/java/alcoholboot/toastit/feature/defaultcocktail/controller/CocktailControllerTest.java
  src/test/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceImplTest.java
  src/test/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceTest.java
  src/test/java/alcoholboot/toastit/feature/user/controller/LikeControllerTest.java
  src/test/java/alcoholboot/toastit/feature/user/service/LikeServiceImplTest.java
Labels: ✨ Feat, 🛠️ Refactor, 📛 Rename

#34 🔀 Merge : "feature/userResign 브랜치 병합
  src/main/java/alcoholboot/toastit/feature/customcocktail/controller/CustomCocktailController.java
Labels: ✨ Feat

#37 🔀 Merge : "feature/userFollw 브랜치 병합
  src/main/resources/templates/feature/customcocktail/customdetail.html
Labels: 🐞 Fix

#39 🔀 Merge : "Feature/categorysearch 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/domain/Cocktail.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/entity/CocktailDocument.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/Impl/CustomCocktailRepositoryImpl.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceImpl.java
  src/main/resources/static/css/defaultcocktail/defaultcocktail.css
  src/main/resources/static/js/defaultcocktail/toggle.js
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailDetails.html
  src/main/resources/templates/feature/defaultcocktail/cocktailGlass.html
  src/main/resources/templates/feature/defaultcocktail/cocktailIngredient.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
  src/main/resources/templates/feature/defaultcocktail/cocktailType.html
Labels: ✨ Feat, 💄 Design

#40 🔀 Merge : "Feature/userFollow 브랜치 병합"
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/java/alcoholboot/toastit/feature/customcocktail/repository/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/customcocktail/service/CustomCocktailService.java
  src/main/java/alcoholboot/toastit/feature/maps/MapController.java
  src/main/java/alcoholboot/toastit/global/config/security/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/static/image/ads/ad1.png
  src/main/resources/static/image/ads/ad2.png
  src/main/resources/static/image/ads/ad3.png
  src/main/resources/static/image/ads/ad4.png
  src/main/resources/static/image/ads/ad5.png
  src/main/resources/static/image/ads/ad6.png
  src/main/resources/static/image/dateCocktail.png
  src/main/resources/static/image/mapcocktail.png
  src/main/resources/static/image/ramdomcock.png
  src/main/resources/static/image/setting.png
  src/main/resources/static/image/wheather.png
  src/main/resources/templates/feature/maps/main.html
  src/main/resources/templates/index.html
Labels: ✨ Feat, 💄 Design

#42 🔀 Merge : "Feature/userFollow 브랜치 병합"
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/resources/static/image/ads/ad3.png
  src/main/resources/templates/feature/customcocktail/customdetail.html
  src/main/resources/templates/feature/defaultcocktail/cocktailDetails.html
  src/main/resources/templates/feature/maps/main.html
  src/main/resources/templates/index.html
Labels: 🐞 Fix

#44 🔀 Merge : "feature/custom 브랜치 병합"
  src/main/resources/static/image/custom-banner.png
  src/main/resources/static/image/like-button.png
  src/main/resources/templates/feature/customcocktail/customdetail.html
  src/main/resources/templates/feature/customcocktail/custommain.html
  src/main/resources/templates/feature/customcocktail/edit.html
  src/main/resources/templates/feature/customcocktail/write.html
Labels: 🛠️ Refactor, 💄 Design

#43 🔀 Merge : "feature/categorysearch 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/controller/CocktailController.java
  src/main/resources/static/js/defaultcocktail/formVail.js
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailGlass.html
  src/main/resources/templates/feature/defaultcocktail/cocktailIngredient.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
  src/main/resources/templates/feature/defaultcocktail/cocktailType.html
Labels: 🐞 Fix, 💄 Design

#48 🔀 Merge : "Feature/recommendByLocation 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/CocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/maps/MapController.java
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/Controller/RecommendByLocationController.java
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/Entity/RecommendByLocation.java
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/Repository/RecommendByLocationRepository.java
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/Service/RecommendByLocationService.java
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/dto/IngredientDTO.java
  src/main/resources/templates/feature/maps/main.html
Labels: ✨ Feat, 💄 Design

#50 🔀 Merge : "feature/categorysearch 브랜치 병합"
  src/main/resources/static/css/defaultcocktail/defaultcocktail.css
  src/main/resources/static/css/defaultcocktail/defaultcocktailrandom.css
  src/main/resources/static/image/cocktail-banner.jpg
  src/main/resources/static/image/defaultcocktail/에그 노그 4.jpg
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailDetails.html
  src/main/resources/templates/feature/defaultcocktail/cocktailGlass.html
  src/main/resources/templates/feature/defaultcocktail/cocktailIngredient.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
  src/main/resources/templates/feature/defaultcocktail/cocktailType.html
  src/main/resources/templates/feature/defaultcocktail/random.html
Labels: 💄 Design

#51 🔀 Merge : "Feature/recommendByLocation브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/Controller/RecommendByLocationController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/resources/templates/feature/customcocktail/customdetail.html
  src/main/resources/templates/index.html
Labels: 🐞 Fix

#52 🔀 Merge : "feature/recommendByLocation브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/Controller/RecommendByLocationController.java
  src/main/resources/templates/feature/defaultcocktail/cocktailDetails.html
  src/main/resources/templates/feature/maps/main.html
Labels: 🐞 Fix

#53 Feature/recommend by location
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/Repository/RecommendByLocationRepository.java
Labels: 🐞 Fix

#54 🔀 Merge : "feature/security 브랜치 병합"
  src/main/java/alcoholboot/toastit/auth/common/PrincipalDetails.java
  src/main/java/alcoholboot/toastit/auth/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/alcoholboot/toastit/auth/oauth2/domain/OAuthAttributes.java
  src/main/java/alcoholboot/toastit/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/alcoholboot/toastit/feature/user/controller/request/UserJoinRequest.java
  src/main/java/alcoholboot/toastit/feature/user/domain/User.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/java/alcoholboot/toastit/feature/user/repository/UserRepository.java
  src/main/java/alcoholboot/toastit/feature/user/service/UserService.java
  src/main/java/alcoholboot/toastit/feature/user/service/impl/UserServiceImpl.java
  src/main/resources/application-oauth.yml
  src/main/resources/templates/feature/user/loginForm.html
Labels: ✨ Feat, 🛠️ Refactor

#56 ✨ Feat : "깃허브 디스코드 알림 봇 추가"
  .github/workflows/discord-notification.yml
  .github/workflows/messages.json
Labels: ✨ Feat

#57 🔀 Merge : "feature/categorysearch 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/Impl/CustomCocktailRepositoryImpl.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceImpl.java
  src/main/resources/static/css/defaultcocktail/defaultcocktail.css
  src/main/resources/static/css/defaultcocktail/defaultcocktaildetail.css
  src/main/resources/static/js/defaultcocktail/detail.js
  src/main/resources/static/js/defaultcocktail/formVail.js
  src/main/resources/static/js/defaultcocktail/search.js
  src/main/resources/static/js/defaultcocktail/toggle.js
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailDetails.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
Labels: 🛠️ Refactor, 💄 Design

#58 💄 Design : "defaultcocktail.css 수치 조정"
  src/main/resources/static/css/defaultcocktail/defaultcocktail.css
Labels: 💄 Design

#63 🔀 Merge : "feature/bugfix 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/recommendByLocation/Controller/RecommendByLocationController.java
Labels: 🐞 Fix

#64 🔀 Merge : "feature/bugfix 브랜치 병합"
  src/main/resources/static/image/login/kakaoLogin.png
  src/main/resources/static/image/login/naverLogin.png
  src/main/resources/templates/feature/user/loginForm.html
Labels: 🐞 Fix, 💄 Design

#65 🔀 Merge : "feature/categorysearch 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/CocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/Impl/CustomCocktailRepositoryImpl.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceImpl.java
  src/main/resources/static/js/defaultcocktail/detail.js
  src/main/resources/static/js/defaultcocktail/list.js
  src/main/resources/static/js/defaultcocktail/search.js
  src/main/resources/static/js/defaultcocktail/toggle.js
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailGlass.html
  src/main/resources/templates/feature/defaultcocktail/cocktailIngredient.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
  src/main/resources/templates/feature/defaultcocktail/cocktailType.html
Labels: 📖 Docs, 🐞 Fix

#66 🔀 Merge : "feature/userFollow 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/user/controller/FollowController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/UserController.java
  src/main/resources/templates/feature/user/followingForm.html
  src/main/resources/templates/feature/user/mypageForm.html
Labels: 🐞 Fix

#67 🔀 Merge : "feature/custom 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/recommendByDate/controller/RecommendByDateController.java
  src/main/java/alcoholboot/toastit/feature/recommendByDate/entity/RecommendByDate.java
  src/main/java/alcoholboot/toastit/feature/recommendByDate/repository/RecommendByDateRepository.java
  src/main/java/alcoholboot/toastit/feature/recommendByDate/service/RecommendByDateService.java
  src/main/resources/templates/feature/date/main.html
Labels: ✨ Feat, 🛠️ Refactor, 💄 Design

#60 🔀 Merge : "feature/api 브랜치 병합"
  .gitignore
  build.gradle
  package-lock.json
  src/main/java/alcoholboot/toastit/feature/api/controller/WeatherController.java
  src/main/java/alcoholboot/toastit/feature/api/dto/AreaRequestDTO.java
  src/main/java/alcoholboot/toastit/feature/api/dto/LatXLngY.java
  src/main/java/alcoholboot/toastit/feature/api/dto/WeatherApiResponseDTO.java
  src/main/java/alcoholboot/toastit/feature/api/dto/WeatherBodyDTO.java
  src/main/java/alcoholboot/toastit/feature/api/dto/WeatherDTO.java
  src/main/java/alcoholboot/toastit/feature/api/dto/WeatherHeaderDTO.java
  src/main/java/alcoholboot/toastit/feature/api/dto/WeatherItemDTO.java
  src/main/java/alcoholboot/toastit/feature/api/dto/WeatherItemsDTO.java
  src/main/java/alcoholboot/toastit/feature/api/dto/WeatherResponseDTO.java
  src/main/java/alcoholboot/toastit/feature/api/entity/RecommendByWeatherEntity.java
  src/main/java/alcoholboot/toastit/feature/api/repository/RecommendByWeatherRepository.java
  src/main/java/alcoholboot/toastit/feature/api/repository/WeatherMapper.java
  src/main/java/alcoholboot/toastit/feature/api/service/RecommendByWeatherService.java
  src/main/java/alcoholboot/toastit/feature/api/service/WeatherService.java
  src/main/java/alcoholboot/toastit/feature/api/service/WeatherServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/image/weather/icons/clear.png
  src/main/resources/static/image/weather/icons/rain.png
  src/main/resources/static/image/weather/icons/snow.png
  src/main/resources/templates/feature/api/mappers/WeatherMapper.xml
  src/main/resources/templates/feature/api/weather.html
Labels: ✨ Feat

#70 🔀 Merge : "feature/design 브랜치 병합"
  src/main/resources/static/js/main/swiper.js
  src/main/resources/templates/index.html
Labels: 💄 Design

#71 🔀 Merge : "feature/design 브랜치 병합"
  src/main/resources/static/css/fragment/navbar-fragment.css
  src/main/resources/templates/feature/customcocktail/custommain.html
  src/main/resources/templates/feature/user/followingForm.html
  src/main/resources/templates/index.html
Labels: 💄 Design

#72 🔀 Merge : "feature/design 브랜치 병합"
  src/main/resources/static/css/user/joinForm.css
  src/main/resources/static/js/user/joinForm.js
  src/main/resources/templates/feature/user/joinForm.html
Labels: 💄 Design

#73 🔀 Merge : "feature/recommendByLocaion 브랜치 병합"
  src/main/resources/templates/feature/maps/main.html
Labels: ✨ Feat

#74 🔀 Merge : "feature/ recommendByLocation 브랜치 병합"
  src/main/resources/templates/feature/maps/main.html
  src/main/resources/templates/fragment/navbar-fragment.html
  src/main/resources/templates/index.html
Labels: 📖 Docs

#75 🔀 Merge : "feature/categorysearch 브랜치 병합"
  src/main/resources/static/css/defaultcocktail/defaultcocktail.css
  src/main/resources/static/js/defaultcocktail/toggle.js
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
Labels: 💄 Design

#80 🔀 Merge : "feature/custom 브랜치 병합"
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/java/alcoholboot/toastit/feature/amazonimage/domain/Image.java
  src/main/java/alcoholboot/toastit/feature/calendarcocktail/controller/CalendarCocktailController.java
  src/main/java/alcoholboot/toastit/feature/calendarcocktail/entity/CalendarCocktail.java
  src/main/java/alcoholboot/toastit/feature/calendarcocktail/repository/CalendarCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/calendarcocktail/repository/RecommendByDateRepository.java
  src/main/java/alcoholboot/toastit/feature/calendarcocktail/service/CalendarCocktailService.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/CraftCocktailController.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/domain/CraftCocktail.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/domain/Ingredient.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/repository/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/service/CraftCocktailService.java
  src/main/java/alcoholboot/toastit/feature/user/controller/FollowController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Like.java
  src/main/java/alcoholboot/toastit/feature/user/entity/LikeEntity.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/resources/templates/feature/craftcocktail/craftdetail.html
  src/main/resources/templates/feature/craftcocktail/craftmain.html
  src/main/resources/templates/feature/craftcocktail/edit.html
  src/main/resources/templates/feature/craftcocktail/write.html
  src/main/resources/templates/feature/date/main.html
  src/main/resources/templates/fragment/navbar-fragment.html
  src/main/resources/templates/index.html
Labels: 🛠️ Refactor, 💄 Design

#83 🔀 Merge : "feature/categorysearch 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/controller/CocktailController.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/repository/custom/Impl/CustomCocktailRepositoryImpl.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/CocktailService.java
  src/main/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceImpl.java
  src/main/resources/static/css/defaultcocktail/defaultcocktail.css
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
  src/main/resources/templates/feature/defaultcocktail/name.html
Labels: ✨ Feat, 💄 Design

#87 🔀 Merge : "feature/localcocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/localcocktail/entity/LocationCocktailEntity.java
  src/main/java/alcoholboot/toastit/feature/localcocktail/repository/LocationCocktailRepository.java
Labels: ❗️ HOTFIX

#88 🔀 Merge : "feature/seasonalcocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/seasonalcocktail/entity/SeasonalCocktailEntity.java
  src/main/java/alcoholboot/toastit/feature/seasonalcocktail/repository/SeasonalCocktailRepository.java
Labels: ⚙️ Config

#90 🔀 Merge : "feature/craftcocktail 브랜치 병합"
  src/main/java/alcoholboot/toastit/HomeController.java
  src/main/java/alcoholboot/toastit/feature/amazonimage/domain/Image.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/CraftCocktailController.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/request/CraftCocktailCreateRequest.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/entity/CraftCocktailEntity.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/entity/IngredientEntity.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/repository/CraftCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/repository/CustomCocktailRepository.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/service/CraftCocktailService.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/service/impl/CraftCocktailServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/user/controller/FollowController.java
  src/main/java/alcoholboot/toastit/feature/user/controller/LikeController.java
  src/main/java/alcoholboot/toastit/feature/user/domain/Like.java
  src/main/java/alcoholboot/toastit/feature/user/entity/LikeEntity.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/resources/templates/feature/craftcocktail/craftdetail.html
  src/main/resources/templates/feature/craftcocktail/edit.html
  src/main/resources/templates/feature/craftcocktail/write.html
  src/main/resources/templates/feature/defaultcocktail/cocktailComplex.html
  src/main/resources/templates/feature/defaultcocktail/cocktailDetails.html
  src/main/resources/templates/feature/defaultcocktail/cocktailList.html
Labels: 🛠️ Refactor

#93 🔀 Merge : "feature/image 브랜치 병합"
  src/main/java/alcoholboot/toastit/feature/amazonimage/controller/ImageUploadController.java
  src/main/java/alcoholboot/toastit/feature/amazonimage/repository/ImageRepository.java
  src/main/java/alcoholboot/toastit/feature/amazonimage/service/ImageService.java
  src/main/java/alcoholboot/toastit/feature/amazonimage/service/S3imageUploadService.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/controller/CraftCocktailController.java
  src/main/java/alcoholboot/toastit/feature/craftcocktail/entity/CraftCocktailEntity.java
  src/main/java/alcoholboot/toastit/feature/image/controller/ImageController.java
  src/main/java/alcoholboot/toastit/feature/image/entity/ImageEntity.java
  src/main/java/alcoholboot/toastit/feature/image/repository/ImageRepository.java
  src/main/java/alcoholboot/toastit/feature/image/service/CloudStorageService.java
  src/main/java/alcoholboot/toastit/feature/image/service/ImageService.java
  src/main/java/alcoholboot/toastit/feature/image/service/impl/CloudStorageServiceImpl.java
  src/main/java/alcoholboot/toastit/feature/image/util/FileUtil.java
  src/main/java/alcoholboot/toastit/feature/user/controller/UserController.java
  src/main/java/alcoholboot/toastit/feature/user/entity/UserEntity.java
  src/main/java/alcoholboot/toastit/global/config/security/SecurityConfig.java
  src/test/java/alcoholboot/toastit/feature/defaultcocktail/controller/CocktailControllerTest.java
  src/test/java/alcoholboot/toastit/feature/defaultcocktail/service/impl/CocktailServiceTest.java
  src/test/java/alcoholboot/toastit/feature/image/controller/ImageUploadControllerTest.java
  src/test/java/alcoholboot/toastit/feature/user/controller/LikeControllerTest.java
  src/test/java/alcoholboot/toastit/feature/user/service/LikeServiceImplTest.java
Labels: 🛠️ Refactor
